services:

  core:
    image: docker.io/lineadicomando/ansvile-core:${VERSION:-latest}
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true
    container_name: ansvil-core
    hostname: ansvil-core
    depends_on:
      - semaphore-db
    network_mode: host
    volumes:
      - ${ANSVIL_DATA_VOLUME_PATH}/venv:/venv:z
      - ${ANSVIL_DATA_VOLUME_PATH}/ansvil:/ansvil:z
      - ${ANSVIL_DATA_VOLUME_PATH}/entrypoint.d:/usr/local/entrypoint.d:z
    environment:
      - ANSVIL_USER=ansvil
      - ANSVIL_USER_HOME=/ansvil
      - ANSVIL_DEFAULT_PROJECTS_PATH=${ANSVIL_DEFAULT_PROJECTS_PATH}
      - CODE_SERVER_DEFAULT_PASSWORD=${CODE_SERVER_DEFAULT_PASSWORD}
      - SEMAPHORE_DB_HOST=${SEMAPHORE_DB_HOST}
      - SEMAPHORE_DB_PORT=${SEMAPHORE_DB_PORT}
      - SEMAPHORE_DB_NAME=${SEMAPHORE_DB_NAME}
      - SEMAPHORE_DB_USER=${SEMAPHORE_DB_USER}
      - SEMAPHORE_DB_PASS=${SEMAPHORE_DB_PASS}
      - SEMAPHORE_ADMIN_USER=${SEMAPHORE_ADMIN_USER}
      - SEMAPHORE_ADMIN_DEFAULT_PASSWORD=${SEMAPHORE_ADMIN_DEFAULT_PASSWORD}
      - SEMAPHORE_ADMIN_NAME=${SEMAPHORE_ADMIN_NAME}
      - SEMAPHORE_ADMIN_EMAIL=${SEMAPHORE_ADMIN_EMAIL}
    restart: unless-stopped

  semaphore-db:
    image: mariadb:10.11
    container_name: ansvil-semaphore-db
    environment:
      - MARIADB_ROOT_PASSWORD=${SEMAPHORE_DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${SEMAPHORE_DB_NAME}
      - MARIADB_USER=${SEMAPHORE_DB_USER}
      - MARIADB_PASSWORD=${SEMAPHORE_DB_PASS}
    volumes:
      - ${SEMAPHORE_VOLUME_PATH}:/var/lib/mysql:z
    network_mode: host
    restart: unless-stopped

  front:
    image: nginx:stable
    container_name: ansvil-proxy
    hostname: ansvil-proxy
    entrypoint: [ "/bin/sh", "/entrypoint.sh" ]
    volumes:
      - ./front/reverse-proxy.conf:/etc/nginx/conf.d/default.conf:ro,z
      - ./front/entrypoint.sh:/entrypoint.sh:ro,z
      - ./front/html:/usr/share/html:z
      - ./data/ssl/certs:/etc/ssl/certs:z
      - ./data/ssl/private:/etc/ssl/private:z
    depends_on:
      - core
    network_mode: host
    environment:
      - SSL_DAYS=${SSL_DAYS}
      - SSL_C=${SSL_C}
      - SSL_ST=${SSL_ST}
      - SSL_L=${SSL_L}
      - SSL_O=${SSL_O}
      - SSL_CN=${SSL_CN}
    restart: unless-stopped
